# Generated by Django 4.1.7 on 2023-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0004_countries_excourses_profile_tour_remove_films_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excourses',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='priceoftour',
            field=models.IntegerField(),
        ),
    ]
