# Generated by Django 4.1.7 on 2023-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba', '0005_alter_excourses_price_alter_tour_priceoftour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(),
        ),
    ]
